### ISSUE TITLE
Census data is slightly off

### ISSUE THREAD

**Issue by jakewalker56** [thiscoldhouse/apportionment-calculator#1]
Fellow OA listener here :) responding to most recent episode re: adding 89 people to NY doesn't give an additional rep-

It looks like the data you pulled from Wikipedia is actually incorrect for the purposes of apportionment- the Wikipedia article includes only current residents, while the official apportionment numbers include current residents + overseas residents (military, etc).  Changes are overall very small, but in NY case seem to matter.  You can find the official apportionment numbers here: https://www.census.gov/data/tables/2020/dec/2020-apportionment-data.html

**Comment by thiscoldhouse** [comment]
Hey I just realized I forgot to close/respond to this, but here I am two years later to say thanks for your report, and I did fix it upon seeing your bug report. Take care!
